site_name: Incogniton Documentation
site_url: https://incognitondocs.com
theme:
  logo: assets/logo/incognitonlogo-removebg-preview.png
  name: material
  palette:
    scheme: white
    primary: purple


nav:
  - Home: "index.md"
  - Profile Setup: "profile.md"
  - Proxy Management: "proxy.md"
  - Testing Profile FingerPrint: "testingProfileFingerPrint.md"
  - Troubleshooting: "troubleshooting.md"
  - Glossary: "glossary.md"

markdown_extensions:
  - admonition
  - pymdownx.details